---
- hosts: data
  vars:
    become: yes
    become_method: sudo
    become_user: ubuntu
   
  tasks:
  - name: Copy hadoop env shell file to servers
    copy: src=../hadoop/files/hadoop-env.sh dest=~/hadoop/hadoop-2.7.0/etc/hadoop/hadoop-env.sh
    become: yes

  
  - name: start Hadoop daemon on data servers
    shell: /root/hadoop/hadoop-2.7.0/sbin/hadoop-daemon.sh --script hdfs start datanode 
    become: yes

  - name: start Yarn daemon on data servers
    shell: /root/hadoop/hadoop-2.7.0/sbin/yarn-daemon.sh start nodemanager
    become: yes

