---
- hosts: master
  vars:
    become: yes
    become_method: sudo
    become_user: ubuntu

  tasks:

  - name: stop Hadoop daemon on master server
    shell: /root/hadoop/hadoop-2.7.0/sbin/hadoop-daemon.sh --script hdfs stop namenode
    become: yes

  - name: stop Yarn daemon on master server
    shell: /root/hadoop/hadoop-2.7.0/sbin/yarn-daemon.sh stop resourcemanager
    become: yes

